version: '3.8'

services:
  eureka-server:
    container_name: eureka
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
  service-currency:
    container_name: service-currency
    build:
      context: ./service-currency
      dockerfile: Dockerfile
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
    ports:
      - "8080:8080"

  service-pricehistory:
    container_name: service-pricehistory
    build:
      context: ./service-pricehistory
      dockerfile: Dockerfile
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
    ports:
      - "8081:8081"

  service-statsanalysis:
    container_name: service-statsanalysis
    build:
      context: ./service-statsanalysis
      dockerfile: Dockerfile
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
    ports:
      - "8082:8082"

  api-gateway:
    container_name: api-gateway
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka/
    depends_on:
      - service-currency
      - service-pricehistory
      - service-statsanalysis
    ports:
      - "8765:8765"