server:
  error:
    include-message: always
    include-stacktrace: never
  port: 8080

spring:
  application:
    name: currency
  devtools:
    add-properties: false


app:
  pairList:
    -
      name: EUR/USD
      price: 1.0174
    -
      name: USD/RUB
      price: 61.1105
    -
      name: CNY/RUB
      price: 8.9804

