server:
  port: 8080

spring:
  application:
    name: currency
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  datasource:
    url: 'jdbc:h2:mem:testdb'
    driverClassName: org.h2.Driver
    username: usertest
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

api:
  currency:
    pair: 'EUR/USD'
  default:
    quantity: '10'
    timeZone: 'EET'
  access:
    key: '98707e3a4a4d44c4b01320395e768297'

