server:
  port: 8081

spring:
  application:
    name: eserver

eureka:
  server:
    wait-time-in-ms-when-sync-empty: 0
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
